# -*- mode: ruby -*-
# vi: set ft=ruby :

# ** Local envs provisioning **
#
# Server #1 - Ansible node (Debian 8)
# Server #2 - Docker server (Debian 8)
#

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.define "ansnode", primary: true do |ansnode|
    ansnode.vm.hostname = "ansnode"
    ansnode.vm.network "private_network", ip: "192.168.11.101"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "ansnode"
      vb.memory = "256"
    end
    ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    ansnode.vm.provision "shell", path: "lib/user.sh", args: "dethroner"
    ansnode.vm.provision "shell", path: "lib/ansible.sh"

  end
  config.vm.define :doc do |doc|
	doc.vm.hostname = "doc-server"
    doc.vm.network "private_network", ip: "192.168.11.111"
    doc.vm.provider "virtualbox" do |vb|
      vb.name = "doc-server"
      vb.memory = "1024"
    end
    doc.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    doc.vm.provision "shell", path: "lib/user-slave.sh", args: "dethroner"

  end  
end