# -*- mode: ruby -*-
# vi: set ft=ruby :

# ** Local envs provisioning **
#
# Server #1 - Ansible node (Debian 8)
# Server #2 - MOB server with predefined 'minecraft' user (Debian 8)
#

# pre-reqs:
#
# ~/.ssh/{id_rsa_mobdeploy.pem, id_rsa_mobdeploy.pub} - deployment key, added to mob-server repo
# ~/.ssh/{id_rsa_mobadmin.pem, id_rsa_mobadmin.pub} - MOB-Admin user key
# these keys should be placed in the repo ./vagrant/ssh or in ~/.ssh folder on your host
#

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.define "ansnode", primary: true do |ansnode|
    ansnode.vm.network "private_network", ip: "192.168.11.101"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "ansnode"
      vb.memory = "256"
    end
    ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    ansnode.vm.provision "shell", path: "lib/user.sh", args: "dethroner"
    ansnode.vm.provision "shell", path: "lib/ansible.sh"

  end
end