# -*- mode: ruby -*-
# vi: set ft=ruby :

# ** Local envs provisioning **
#
# Server #1 - Ansible node (Debian 8)
# 
#

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.define "ansnode", primary: true do |ansnode|
    ansnode.vm.network "private_network", ip: "192.168.11.101"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "ansnode"
      vb.memory = "256"
    end
    ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    ansnode.vm.provision "shell", path: "lib/user.sh", args: "dethroner"
    ansnode.vm.provision "shell", path: "lib/ansible.sh"

  end
end